### ISSUE TITLE
TransFireBot

### ISSUE THREAD

**Issue by Serena1997zx** [Haisyer/TransFireBot#112]
Hi Sir,transfirebot has encountered a problem here. I don’t know how to create a suitable dodo image file. need your help.

**Comment by Haisyer** [comment]
You need to use the API provided by Dodo to upload your local images to the server to get a url that can be used by Dodo.

**FYI**
[https://open.imdodo.com/dev/](url)

After getting the processed url, you need to write it into a txt file in the correct format and fill in the correct path to the txt file in the bot settings.

Since it's not convenient to show pictures here,you can also contact me at tecent qq for more details.

**Comment by Serena1997zx** [comment]
What is the qq number?

**Comment by Haisyer** [comment]
### Group Number 
**_153480143_**

You can get help here

**Comment by Serena1997zx** [comment]
Thank you

**Comment by Serena1997zx** [comment]
被拒绝加入群了大佬

**Comment by Haisyer** [comment]
@8CBCA403 @wubinwww @easyworld 
All of them are administrators, not am I
You can ask them for help joining the group

**Comment by Serena1997zx** [comment]
大佬管理员让我加你qq

**Comment by Haisyer** [comment]
1729883690
